### ISSUE TITLE
v2.1.5 causing failures

### ISSUE THREAD

**Issue by randombitsUK** [ben-eb/postcss-svgo#48]
Hi,

We're seeing errors with the latest version:

```
node_modules/cssnano/node_modules/postcss-svgo/node_modules/svgo/plugins/cleanupIDs.js:123
    for (var ID of referencesIDs) {
```

The error wasn't erroring with v2.1.4. We're using node v0.12.7

We're not pulling in postcss-svgo directly, rather it's being pulled in as a dependency of CSS Nano.

**Comment by ben-eb** [comment]
Seems odd to me, 0.7.0 is supposed to drop support for 0.10 (but minimum Node version is 0.12). Perhaps worth reporting this issue directly in svgo's tracker?

https://github.com/svg/svgo/issues

**Comment by chartzoge** [comment]
@ben-eb You updated to 2.1.5 but upgraded svgo to 0.7 from ~0.6. This is not a patch change, it's a minor change at least. You basically just dropped support for v0.10 by doing a patch release. Doesn't seem correct to me. This also broke our builds, since your package is included in cssnano as ^2.1.1, which is included in gulp-cssnano.

**Comment by ben-eb** [comment]
@chartzoge This module doesn't track svgo's version numbering system, as svgo doesn't use semver (being in pre-1.0.0 for so long) technically every release is breaking. A minor update in this case would not make a difference to breaking a build, only a major version. Should I release a major version for every major svgo release? If they move to a semver system, yes. My only consideration to release a patch here was that my test suite was still passing. I don't officially support 0.10 as I've had a lot of difficulties with that on continuous integration; indeed, 0.10 has not been supported since cssnano 2.x. https://github.com/ben-eb/cssnano/releases/tag/v2.0.0

There's also the fact that 0.10 will be end-of-lifed in about two weeks' time; so I'd recommend moving away from Node 0.10 as soon as possible, preferably to v4 as 0.12 is also on its way out.

See also https://github.com/ben-eb/postcss-svgo/issues/47

**Comment by orbiteleven** [comment]
Unfortunately, the maintainers of svgo don't seem to care about breaking changes in minor releases. While this is no fault of postcss-svgo, it's probably best to pin to svgo@0.6.6 until they fix the breaking change on their end.

**Comment by ben-eb** [comment]
Like I wrote above, I've not supported 0.10 for over a year now; any support for this platform has been coincidental as I don't run any tests with 0.10. So, my apologies if this is an unexpected break for you, however I'm not reverting back to 0.6.6 as 0.7.0 has other fixes & features besides cutting support for 0.10, and anyone using newer versions of Node will not benefit from these if I pin the version.

Again, I'd like to stress that 0.10 is on its way out. Node 4 is faster by ~25% as it uses an updated version of V8, so you will experience better build times (at least!) by upgrading. Any short term pain from migrating your Node version at this point will be mitigated in the long term by improved performance.

http://apmblog.dynatrace.com/2015/09/05/all-you-need-to-know-about-node-js-4-0/

**Comment by orbiteleven** [comment]
That's incredibly unfortunate. We're not a direct consumer of postcss-svgo, but rather one of the MANY users of css-loader. The breaking changes in svgo that require Node 0.12.x are arbitrary (using "for in" syntax to loop). 

I would love to upgrade to Node 4, but our infrastructure team has it's reasons for sticking with 0.10.x (the devil you know stuff, I assume), and it's not something all downstream consumers of your package can control. 

I swear I'm not looking a gift horse in the mouth, and I do thank the team for its work. I guess it's your package to manage and "you do you", but it's not being a "good citizen" to introduce breaking changes in minor releases. I understand that the maintainers of svgo are ultimately the ones at fault, but if you really need the changes in svgo@0.7.0 and know it contains breaking changes, it would be better to introduce that as a major release.

**Comment by ben-eb** [comment]
It's worth noting that [css-loader specifies 0.12 as a minimum version](https://github.com/webpack/css-loader/commit/3d9dda4822d9b2fe64bb094303465ae83d57530a) since January. If you're not going to upgrade now, then when?

**Comment by ben-eb** [comment]
@orbiteleven Looks like we might get our wishes granted here. 😄

https://github.com/svg/svgo/issues/602#issuecomment-249652639

**Comment by ben-eb** [comment]
svgo 0.7.1 is out so I'm going to close this.
